### ISSUE TITLE
how to wrap a number within a range, if the minimum isnt 0?

### ISSUE THREAD

**Issue by cabfile** [semibran/wrap-around#2]
i cant seem to find an answer to this, aside from some random lua answer

**Comment by semibran** [comment]
you may just need to normalize the inputs first -- so if you needed to wrap eg. 2 between 5 and 10 that'd just be `wrap(10 - 5, 2) + 5`, or more generically:
```js
const wrapRange = (min, max, n) =>
  wrap(max - min, n) + min
```

Not sure if that's the kind of thing you're looking for

**Comment by cabfile** [comment]
i forgot that i have managed to find an answer to this myself and i forgot to close the issue haha
